name: Sjoslaget
description: Front-end for the new Sjoslaget.se web site.
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.2
  angular_forms: ^2.0.0
  angular_router: ^2.0.0-alpha
  chartjs:
    git:
      url: https://github.com/google/chartjs.dart.git
  decimal:
  frontend_shared:
    path: ../FrontendShared
  oauth2:
    git:
      url: https://github.com/wsv-accidis/oauth2.git
  quiver: '>=0.24.0 <0.30.0'

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
