name: Sjoslaget
description: Front-end for the new Sjoslaget.se web site.
version: 0.0.1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  angular: ^6.0.0
  angular_components: ^1.0.2
  angular_forms: ^3.0.0
  angular_router: ^2.0.0
  chartjs:
    git:
      url: https://github.com/google/chartjs.dart.git
  decimal:
  frontend_shared:
    path: ../FrontendShared
  oauth2:
    git:
      url: https://github.com/wsv-accidis/oauth2.git
  quiver: '>=2.0.0 <3.0.0'

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.9.0
  build_test: ^1.0.0
  build_web_compilers: '>=2.12.0 <3.0.0'
  test: ^1.6.3
