name: Gotland
description: Front-end for the AbsolutGotland.se web site.
version: 0.0.1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0
  angular_forms: ^2.1.2
  angular_router: ^2.0.0-alpha
  frontend_shared:
    path: ../FrontendShared
  quiver: '>=2.0.0 <3.0.0'

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.0.0
  build_test: ^0.10.2+5
  build_web_compilers: ^1.0.0
  test: ^1.3.0
