name: frontend_shared
description: Frontend shared
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0
  corsac_jwt:
    git: https://github.com/corsac-dart/jwt.git
  decimal:
  http:
  intl:
  oauth2:
    git:
      url: https://github.com/wsv-accidis/oauth2.git
  quiver: '>=2.0.0 <3.0.0'
