name: frontend_shared
description: Frontend Shared Components
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  angular: ^6.0.1
  angular_components: ^1.0.3
  corsac_jwt: ^0.2.2
  decimal:
  http: ^0.12.0
  intl:
  oauth2:
    git:
      url: https://github.com/wsv-accidis/oauth2.git
  quiver: '>=2.0.0 <3.0.0'
