name: frontend_shared
description: Frontend shared
version: 0.0.1

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  corsac_jwt:
    git: https://github.com/corsac-dart/jwt.git
  decimal:
  http:
  intl:
  oauth2:
    git: https://github.com/wsv-accidis/oauth2.git
  quiver: '>=0.23.0 <0.27.0'
