export 'package:frontend_shared/model/json_field.dart';

const String COUNT = 'Count';
const String COUNTDOWN = 'Countdown';
const String DEPARTURE = 'Departure';
const String DESCRIPTION = 'Description';
const String EMAIL = 'Email';
const String FIRSTNAME = 'FirstName';
const String ID = 'Id';
const String IS_OPEN = 'IsOpen';
const String LASTNAME = 'LastName';
const String NAME = 'Name';
const String NO = 'No';
const String OPENING = 'Opening';
const String PHONE_NO = 'PhoneNo';
const String PLACE_IN_QUEUE = 'PlaceInQueue';
const String PRICE = 'Price';
const String PRICE_PER_PAX = 'PricePerPax';
const String QUEUE_SIZE = 'QueueSize';
const String TEAM_NAME = 'TeamName';
const String TEAM_SIZE = 'TeamSize';
