export 'package:frontend_shared/model/json_field.dart';

const COUNTDOWN = 'Countdown';
const DEPARTURE = 'Departure';
const DESCRIPTION = 'Description';
const EMAIL = 'Email';
const FIRSTNAME = 'FirstName';
const ID = 'Id';
const IS_OPEN = 'IsOpen';
const LASTNAME = 'LastName';
const NAME = 'Name';
const NO = 'No';
const OPENING = 'Opening';
const PHONE_NO = 'PhoneNo';
const PLACE_IN_QUEUE = 'PlaceInQueue';
const PRICE = 'Price';
const PRICE_PER_PAX = 'PricePerPax';
const QUEUE_SIZE = 'QueueSize';
const TEAM_NAME = 'TeamName';
const TEAM_SIZE = 'TeamSize';
