//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accidis.Gotland.WebService.Content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Emails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Emails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Accidis.Gotland.WebService.Content.Emails", typeof(Emails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hej!
        ///
        ///Gratulerar - du har fått plats på {EVENT_NAME}!
        ///
        ///Din bokning med referens {BOOKING_REF} har nu tilldelats ett eller
        ///flera boenden (alternativt tältplats). 
        ///
        ///Gå till absolutgotland.se/bokning och mata in referens samt PIN-kod 
        ///för att visa din bokning och hur mycket du ska betala. Du kommer
        ///på samma sida att kunna se när betalningen kommit in.
        ///
        ///Vårt Bankgiro är 299-5272 och betalningsmottagare är HZ Event &amp; Consulting AB.
        ///Betala så snart som möjligt!
        ///
        ///VIKTIGT: Du måste ange bokningsrefere [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BookingConfirmedEmail {
            get {
                return ResourceManager.GetString("BookingConfirmedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har fått plats på {EVENT_NAME}.
        /// </summary>
        internal static string BookingConfirmedSubject {
            get {
                return ResourceManager.GetString("BookingConfirmedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hej!
        ///
        ///Det här är en bekräftelse på att din bokning till {EVENT_NAME} är mottagen.
        ///
        ///Din bokningsreferens är {BOOKING_REF} och din PIN-kod är {PIN_CODE}.
        ///
        ///Ta vara på dessa! Du behöver bokningsreferensen för att hämta ut dina
        ///nycklar och tillsammans med PIN-koden för att komma åt din bokning.
        ///
        ///Gå till absolutgotland.se/bokning och mata in referens samt PIN-kod 
        ///för att visa din bokning. Du kan göra ändringar en kort tid efter
        ///bokningsstart, därefter kan du se status på bokningen och om
        ///du fått plat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BookingCreatedEmail {
            get {
                return ResourceManager.GetString("BookingCreatedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Din bokning till {EVENT_NAME}.
        /// </summary>
        internal static string BookingCreatedSubject {
            get {
                return ResourceManager.GetString("BookingCreatedSubject", resourceCulture);
            }
        }
    }
}
